### ISSUE TITLE
Optimal blob tracking

### ISSUE THREAD

**Issue by JocelynVelarde** [RoBorregos/robocup-soccer-open-2024#6]
- [x] Use LAB values for orange ball
- [x] Draw box and cross inside blob
- [x] Print 'x' and 'y' coordinates
- [x] Find distance
- [x] Find angle
